version: '2'

services:

  web:
    image: 'netcore-webapp-postgres'
    container_name: 'netcore-webapp-postgres'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "8080:5000"
    depends_on:
     - "postgres"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-network    

networks:
  aspnetcoreapp-network:
    driver: bridge

    